In [94]:
import numpy as np

In [107]:
print("-------_________reshape__________---------")
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.shape)
print(arr.reshape(3,4),"\n")
print("reshape 3 parameters\n",arr.reshape(2,3,2))
print("reshape =  ",arr.reshape(2,3,2).ndim)
print("reshape base =  ",arr.reshape(2,3,2).base)



-------_________reshape__________---------
(12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

reshape 3 parameters
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
reshape =   3
reshape base =   [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [110]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [111]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]
