In [28]:
import numpy as np

In [32]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[0])
print(arr[9])
print(arr[2]+arr[5])

1
10
9


In [50]:

print("------2 D array --------\n\n")
twoD_arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("3nd element of first row = ",twoD_arr[0,2])
print("5nd element of the second row= ",twoD_arr[1,4])
print("Add 2nd element of the first row and 3rd element of the second row =",twoD_arr[0,1]+twoD_arr[1,2])
print("2nd row last element =",twoD_arr[1,-1])
print("1st row second last element = ",twoD_arr[0,-2])

print("----------\n")

print("------3 D array --------\n\n")
thirdD_arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(thirdD_arr)
print("----------\n")
print(thirdD_arr[0,0,0])
print(thirdD_arr[0,1,0])
print(thirdD_arr[0,1,2])
print(thirdD_arr[1,0,0])
print(thirdD_arr[1,1,0])
print(thirdD_arr[1,1,1])



------2 D array --------


3nd element of first row =  3
5nd element of the second row=  10
Add 2nd element of the first row and 3rd element of the second row = 10
2nd row last element = 10
1st row second last element =  4
----------

------3 D array --------


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
----------

1
4
6
7
10
11


In [69]:
print("--Slicing______--------\n")
print(arr[2:])
print(arr[:4])
print(arr[-3:-2])
print(arr[1:10:1])
print(arr[2:9:2])
print(arr[0:10:3])
print(arr[::3])
print(arr[0:10:2])
print(arr[::2])


print("--___2 D__Slicing______--------\n")
print(twoD_arr[1,1:2])
print(twoD_arr[1,1:])
print(twoD_arr[1,::2])
print(twoD_arr[0:4,1])
print("s1--->",twoD_arr[0:5,1:4])




--Slicing______--------

[ 3  4  5  6  7  8  9 10]
[1 2 3 4]
[8]
[ 2  3  4  5  6  7  8  9 10]
[3 5 7 9]
[ 1  4  7 10]
[ 1  4  7 10]
[1 3 5 7 9]
[1 3 5 7 9]
--___2 D__Slicing______--------

[7]
[ 7  8  9 10]
[ 6  8 10]
[2 7]
s1---> [[2 3 4]
 [7 8 9]]


In [77]:
print("--_______Array Shapes______--------\n")
print(arr.shape)
print(twoD_arr.shape)
print(thirdD_arr.shape)  #2squere and 3 element

arr1=np.array([1,2,3,4,5],ndmin=5)
print(arr1)
print(arr1.shape)
print(arr1.ndim)

--_______Array Shapes______--------

(10,)
(2, 5)
(2, 2, 3)
[[[[[1 2 3 4 5]]]]]
(1, 1, 1, 1, 5)
5
