In [13]:
import numpy as np

In [15]:
zeroD=np.array(46)
print(zeroD)
print(type(zeroD))
print(zeroD.ndim)

46
<class 'numpy.ndarray'>
0


In [16]:
oneD=np.array([1,2,3,4,5])
print(oneD)
print(type(oneD))
print(oneD.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [23]:
twoD=np.array([[1,2,3,4],[5,6,7,8]])
print(twoD)
print(type(twoD))
print(twoD.ndim)


twoD1=np.array([[1,2,3],[10,20,30]])
print(twoD1)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
2
[[ 1  2  3]
 [10 20 30]]


In [26]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print("---------")
e=np.array([[[123,456,789]]])
print(e.ndim)
print("---------")

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

---------
3
---------
0
1
2
3
